#!/bin/bash

# Install daemon
cp /usr/share/gooroom/security/os-protector/gop-daemon /etc/init.d/
update-rc.d gop-daemon defaults

# Disable interrupt remapping to reserve IOMMU if Gooroom Boot Protector is not installed
service gbp-daemon status > /dev/null
ret=$?
if [ \( $ret -ne 0 \) -a \( $ret -ne 3 \) ]; then
	sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT=\"/GRUB_CMDLINE_LINUX_DEFAULT=\"intremap=off /' /etc/default/grub
	update-grub
fi

# Delete previous plka file
rm -f /etc/polkit-1/localauthority/90-mandatory.d/disable-suspend.pkla
rm -f /etc/polkit-1/localauthority/90-mandatory.d/disable-hibernate.pkla
