#!/bin/bash

# Install daemon
cp /usr/share/gooroom/security/os-protector/gop-daemon /etc/init.d/
update-rc.d gop-daemon defaults

# Disable interrupt remapping to reserve IOMMU if Gooroom Boot Protector is not installed
service gbp-daemon status > /dev/null
ret=$?
if [ \( $ret -ne 0 \) -a \( $ret -ne 3 \) ]; then
	sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT=\"/GRUB_CMDLINE_LINUX_DEFAULT=\"intremap=off /' /etc/default/grub
	update-grub
fi

# Disable hibernate and suspend function in systemd config to support notebook
sed -i 's/#HandleSuspendKey=suspend/HandleSuspendKey=ignore/; s/#HandleHibernateKey=hibernate/HandleHibernateKey=ignore/; s/#HandleLidSwitch=suspend/HandleLidSwitch=ignore/' /etc/systemd/logind.conf
sed -i 's/#xserver-command=X/xserver-command=X -s 0 dpms/' /etc/lightdm/lightdm.conf
