#!/bin/sh
### BEGIN INIT INFO
# Provides:          gop-daemon
# Required-Start:
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Gooroom OS Protector service
# Description:       Gooroom OS Protector protects the OS kernel and drivers.
### END INIT INFO

set -e

GOP_HELPER_PATH="/usr/share/gooroom/security/os-protector/gop-helper"
GOP_HELPER_NAME="gop-helper"
PRELOAD_MODULE="/usr/share/gooroom/security/os-protector/preload_module"
SERVICE_NAME="gop-daemon"
SERVICE_PATH="/usr/share/gooroom/security/os-protector/$SERVICE_NAME"
MAIN_DRIVER_NAME="shadow_box"
MAIN_DRIVER_PATH="/usr/share/gooroom/security/os-protector/shadow_box.ko"
HELPER_DRIVER_NAME="shadow_box_helper"
HELPER_DRIVER_PATH="/usr/share/gooroom/security/os-protector/$HELPER_DRIVER_NAME.ko"
TAG_NAME="GOP"

# Check for daemon presence
#[ -x "$GOP_HELPER_PATH" ] || exit 0

OPTIONS=""
MODULES=""

# Get lsb functions
. /lib/lsb/init-functions
ret_value_of_check=0

# Write a syslog message
#  $1 - Message
#  $2 - Error code
#  $3 - Priority
out_log()
{
	/usr/bin/python3 -c "from systemd import journal;journal.send('$TAG_NAME: $1', SYSLOG_IDENTIFIER='$SERVICE_NAME', GRMCODE='$2', PRIORITY=$3)"
}

# Check status of security service
check() {
	GOP_HELPER_LOADED=`ps -e | grep -w $GOP_HELPER_NAME || true`
	if [ \( -f $MAIN_DRIVER_PATH \) -a \( -f $HELPER_DRIVER_PATH \) -a \( -f $GOP_HELPER_PATH \) -a "$GOP_HELPER_LOADED" != "" ]; then
		log_action_msg "$TAG_NAME:" "$SERVICE_NAME active"
		ret_value_of_check=0
	else
		log_action_msg "$TAG_NAME:" "$SERVICE_NAME inactive"
		ret_value_of_check=-1
	fi
}

# OS protector service main
case "$1" in
	start)
		log_daemon_msg "$TAG_NAME" "Start Gooroom OS Protector service"
		log_end_msg 0

		HELPER_LOADED=`lsmod | grep $HELPER_DRIVER_NAME || true`

		# Prevent multiple loading
		if [ "$HELPER_LOADED" = "" ]; then
			$PRELOAD_MODULE
			$GOP_HELPER_PATH
			sleep 3
		fi
		check

		if [ $ret_value_of_check -eq 0 ]; then
			out_log "started successfully" "020001" 6
		else
			out_log "failed to start" "020003" 3
		fi
	;;

	stop)
		log_daemon_msg "$TAG_NAME" "Stop Gooroom OS Protector service"
		log_end_msg 0
		out_log "stoped successfully" "020002" 6
	;;

	enable-autostart)
		log_action_msg "$TAG_NAME" "Enabling autostart"
		update-rc.d $SERVICE_NAME remove
		cp $SERVICE_PATH /etc/init.d/
		update-rc.d $SERVICE_NAME defaults
	;;

	disable-autostart)
		log_action_msg "$TAG_NAME" "Disabling autostart"
		update-rc.d os_protection remove
	;;

	check)
		check
	;;

	*)
		log_action_msg "Usage: /etc/init.d/os_protection {start|stop|enable-autostart|disable-autostart}"
		exit 1
	;;
esac

exit 0
