#!/bin/sh

# Describe preload modules for protection
modprobe ip_tables
modprobe iptable_filter
modprobe xt_owner
modprobe libarc4
modprobe ccm
modprobe ctr
modprobe rfcomm
modprobe usbhid
modprobe hid_generic
modprobe snd_hda_codec_hdmi
modprobe uas
